# [[redirects]]
#   from = "/*"
#   to = "https://caravan-node.herokuapp.com/:splat"
#   status = 301
#   force = false

[[redirects]]
  from = "/api/*"
  to = "https://caravan-node.herokuapp.com/:splat"
  status = 200
