[[redirects]]
  from = "/api/*"
  to = "https://caravan-node.herokuapp.com/api/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/*"
  to = "https://caravan-node.herokuapp.com/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/"
  to = "https://caravan-node.herokuapp.com"
  status = 302
  force = true
